project_id = "jbjlqvwhbvttcfuqajfn"
[functions.mercadopago-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/mercadopago-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mercadopago-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mercadopago-webhook/*.html" ]

[functions.mp-connect]
enabled = true
verify_jwt = true
import_map = "./functions/mp-connect/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-connect/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-connect/*.html" ]

[functions.send-confirmation]
enabled = true
verify_jwt = true
import_map = "./functions/send-confirmation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-confirmation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-confirmation/*.html" ]

[functions.send-cancellation]
enabled = true
verify_jwt = true
import_map = "./functions/send-cancellation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-cancellation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-cancellation/*.html" ]
